name: flutter_inappwebview
description: A Flutter Inappwebview plugin.
version: 6.0.0

environment:
  sdk: ">=2.17.0 <4.0.0"
  flutter: ">=3.0.0"

dependencies:
  flutter:
    sdk: flutter

dev_dependencies:
  flutter_test:
    sdk: flutter

flutter:
  plugin:
    platforms:
      android:
        package: com.pichillilorenzo.flutter_inappwebview
        pluginClass: InAppWebViewFlutterPlugin
        fileName: flutter_inappwebview 
      ios:
        pluginClass: InAppWebViewFlutterPlugin
        fileName: flutter_inappwebview
      web:
        pluginClass: InAppWebViewFlutterPlugin
        fileName: lib/web.dart
      macos:
        pluginClass: InAppWebViewFlutterPlugin
        fileName: macos/Classes/InAppWebViewFlutterPlugin.swift
      windows:
        pluginClass: InAppWebViewFlutterPlugin
        fileName: windows/Classes/InAppWebViewFlutterPlugin.cpp
      linux:
        pluginClass: InAppWebViewFlutterPlugin
        fileName: linux/Classes/InAppWebViewFlutterPlugin.cpp
