name: flutter_inappwebview
description: A Flutter Inappwebview plugin.
version: 6.0.0

environment:
  sdk: ">=2.17.0 <4.0.0"
  flutter: ">=3.0.0"

dependencies:
  flutter:
    sdk: flutter

dev_dependencies:
  flutter_test:
    sdk: flutter

flutter:
  plugin:
    platforms:
      android:
        default_package: flutter_inappwebview_android
      ios:
        default_package: flutter_inappwebview_ios
      macos:
        default_package: flutter_inappwebview_macos
      web:
        default_package: flutter_inappwebview_web
